module.exports = {
    googleClientID: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    googleClientSecret: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    mongoURI: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    cookieKey: 'XXXXXXXX'
};
